-- For table REGION
ALTER TABLE SUPPLIER
ADD PRIMARY KEY (S_SUPPID);
 
-- For table NATION
ALTER TABLE RESTRAUNT
ADD PRIMARY KEY (R_RESTRAUNTID);
 
ALTER TABLE RESTRAUNT
ADD FOREIGN KEY (R_SUPPID) references SUPPLIER;
 
COMMIT WORK;
 
-- For table SUPPLIER
ALTER TABLE RATING
ADD PRIMARY KEY (RA_RATINGID);
 
ALTER TABLE RATING
ADD FOREIGN KEY (RA_RESTRAUNTID) references RESTRAUNT;
 
COMMIT WORK;

-- For table PARTSUPP
ALTER TABLE MENU
ADD PRIMARY KEY (M_RESTRAUNTID,M_ITEMID);
 
COMMIT WORK;
 
-- For table CUSTOMER
ALTER TABLE ITEMS
ADD PRIMARY KEY (I_ITEMID);
 
COMMIT WORK;